### ISSUE TITLE
Unique project name.

### ISSUE THREAD

**Issue by AndreyKoltsov1997** [katevi/Gitlogue#23]
"Chat" is, without a doubt, a representative name for this project, but it's not as unique as it could be. :) 
Please, come up with a name for the project, one word preferably.

**Comment by katevi** [comment]
I have idea "dialogit" =)
It's "dialogue it" (dialogue is like verb = speak about it) and there is git (it is about github)

**Comment by katevi** [comment]
Another ides is "gitlogue" - it is homonym of "git log" (git command), and it is about GitHub and dialogue

**Comment by AndreyKoltsov1997** [comment]
Gitloque is the final name. 👍
